# Generated by Django 5.0.4 on 2024-05-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletrotechapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='PhoneNumber',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='FirstName',
            new_name='UserName',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='LastName',
        ),
        migrations.AddField(
            model_name='customers',
            name='Address',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='customers',
            name='Country',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='customers',
            name='District',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
