# Generated by Django 5.0.4 on 2024-05-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletrotechapp', '0002_rename_phonenumber_customers_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductType', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Price', models.IntegerField()),
                ('Image', models.ImageField(upload_to='static/images/products/')),
                ('availability', models.IntegerField()),
            ],
        ),
    ]
