# Generated by Django 4.2.4 on 2024-06-05 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eletrotechapp', '0005_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eletrotechapp.products')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eletrotechapp.customers')),
            ],
        ),
    ]
