# Generated by Django 4.2.4 on 2024-06-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletrotechapp', '0006_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
